# Site settings
title: MRAE Capstone - WATS 5340 & 5350
description: > # this means to ignore newlines until "baseurl:"
  Watershed Sciences - Management & Restoration of Aquatic Ecosystems Capstone Course
url: http://restoration-usu.github.io
baseurl: "/WATS-5340-5350"

# Build settings
markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


layouts_dir:  src/_layouts
includes_dir: src/_includes

exclude:
  - src
  - LICENSE
  - README.md
  - _config.yml